
language: objective-c
osx_image: xcode9

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8

notifications:
  email: false

before_install:

    - env
    - locale
    - xcpretty --version
    - xcodebuild -version
    - xcodebuild -showsdks

script:
    - set -o pipefail
    - xcodebuild clean build -project Dram.xcodeproj -target 'Dram' -sdk iphonesimulator PLATFORM_NAME=iphonesimulator -configuration Debug | xcpretty
